version: "3.3"

services:
  db:
    image: andresvidal/rpi3-mongodb3
    networks:
      - fire
    ports:
      - 27017:27017

  fireserv:
    image: fire:0.0.6
    build: .
    # environment:
    #   - FIRE_SCAN_HOME="yes"
    #   - FIRE_CWD=/root/fire
    #   - FIRE_DB_ADDR=mongodb://db:27017/ampnadoDB
    #   - FIRE_DOCKER=nodocker

    #   - FIRE_NFOS=/root/fire/nfos 
    #   - FIRE_THUNMBNAILS=/root/fire/thumbnails 

    #   - FIRE_TVSHOWS=/root/tvshows 
    #   - FIRE_MUSIC=/root/music 
    #   - FIRE_MOVIES=/root/movies
    #   - FIRE_USB1=/root/USB1
    #   - FIRE_USB2=/root/USB2
    #   - FIRE_USB3=/root/USB3
    #   - FIRE_PAGINATION=45
    #   # - FIRE_USB4="None"

      
      
    networks:
      - fire
    ports:
      - 6795:6795
    volumes:
      - fire_movies_vol:/root/movies/
      - fire_tvshows_vol:/root/tvshows/
      - fire_thumbnails_vol:/root/fire/thumbnails/
      - fire_nfos_vol:/root/fire/nfos
      - fire_usb1_vol:/root/USB1 
      - fire_usb2_vol:/root/USB2 
      - fire_usb3_vol:/root/USB3 
      # - fire_usb4_vol:/root/USB4
      
    depends_on:
      - db

networks:
  fire:

volumes:
  fire_movies_vol:
    driver: local
    driver_opts:
      type: none
#THIS NEEDS TO BE CHANGE TO THE CORRECT PATH ON THE PI
      device: /home/pi/Videos/Movies
      o: bind

      # need posters volume

  fire_tvshows_vol:
    driver: local
    driver_opts:
      type: none
#THIS NEEDS TO BE CHANGE TO THE CORRECT PATH ON THE PI
      device: /home/pi/Videos/TVShows
      o: bind

  fire_thumbnails_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/pi/Pictures/Thumbnails
      o: bind

  fire_nfos_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/pi/Pictures/NFOS
      o: bind

  fire_usb1_vol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/FOO/media
      o: bind

  fire_usb2_vol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/USB2/media
      o: bind

  fire_usb3_vol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/USB3/media
      o: bind

  # fire_usb4_vol:
    # driver: local
    # driver_opts:
      # type: none
      # device: /media/pi/
      # o: bind